class Type:

    def __init__(self,
                 name: str,
                 color: tuple[int],
                 affinities: dict[str | int]):
        self.name = name
        self.color = color
        self.affinities = affinities

    def affinity_with(self, other: Type):
        return self.affinities[other]

    def __str__(self):
        return self.name.upper()


NORMAL = Type('NORMAL',
              (168, 167, 122),
              {
               'NORMAL': 1,
               'PLANTE': 1,
               'FEU': 1,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 1,
               'COMBAT': 1,
               'POISON': 1,
               'SOL': 1,
               'VOL': 1,
               'PSY': 1,
               'INSECT': 1,
               'ROCHE': 0.5,
               'SPECTR': 0,
               'DRAGON': 1,
               'DARK': 1,
               'ACIER': 0.5,
               'FEE': 1
               })

PLANTE = Type('PLANTE',
              (122, 199, 76),
              {
                  'NORMAL': 1,
                  'PLANTE': 0.5,
                  'FEU': 0.5,
                  'EAU': 2,
                  'ELEK': 1,
                  'GLACE': 1,
                  'COMBAT': 1,
                  'POISON': 0.5,
                  'SOL': 2,
                  'VOL': 0.5,
                  'PSY': 1,
                  'INSECT': 0.5,
                  'ROCHE': 2,
                  'SPECTR': 1,
                  'DRAGON': 1,
                  'DARK': 1,
                  'ACIER': 1,
                  'FEE': 1
              })

FEU = Type('FEU',
           (238, 129, 48),
           {'NORMAL': 1,
            'PLANTE': 2,
            'FEU': 0.5,
            'EAU': 0.5,
            'ELEK': 1,
            'GLACE': 2,
            'COMBAT': 1,
            'POISON': 1,
            'SOL': 1,
            'VOL': 1,
            'PSY': 1,
            'INSECT': 2,
            'ROCHE': 0.5,
            'SPECTR': 1,
            'DRAGON': 0.5,
            'DARK': 1,
            'ACIER': 2,
            'FEE': 1},
           )

EAU = Type('EAU',
           (99, 144, 240),
           {'NORMAL': 1,
            'PLANTE': 0.5,
            'FEU': 2,
            'EAU': 0.5,
            'ELEK': 1,
            'GLACE': 1,
            'COMBAT': 1,
            'POISON': 1,
            'SOL': 2,
            'VOL': 1,
            'PSY': 1,
            'INSECT': 1,
            'ROCHE': 2,
            'SPECTR': 1,
            'DRAGON': 0.5,
            'DARK': 1,
            'ACIER': 1,
            'FEE': 1}
           )

ELEK = Type('ELEK',
            (247, 208, 44),
            {'NORMAL': 1,
             'PLANTE': 0.5,
             'FEU': 1,
             'EAU': 2,
             'ELEK': 0.5,
             'GLACE': 1,
             'COMBAT': 1,
             'POISON': 1,
             'SOL': 0,
             'VOL': 2,
             'PSY': 1,
             'INSECT': 1,
             'ROCHE': 1,
             'SPECTR': 1,
             'DRAGON': 0.5,
             'DARK': 1,
             'ACIER': 1,
             'FEE': 1}
            )

GLACE = Type('GLACE',
             (150, 217, 214),
             {'NORMAL': 1,
              'PLANTE': 2,
              'FEU': 0.5,
              'EAU': 0.5,
              'ELEK': 1,
              'GLACE': 0.5,
              'COMBAT': 1,
              'POISON': 1,
              'SOL': 2,
              'VOL': 2,
              'PSY': 1,
              'INSECT': 1,
              'ROCHE': 1,
              'SPECTR': 1,
              'DRAGON': 2,
              'DARK': 1,
              'ACIER': 0.5,
              'FEE': 1}
             )

COMBAT = Type('COMBAT',
              (194, 46, 40),
              {'NORMAL': 2,
               'PLANTE': 1,
               'FEU': 1,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 2,
               'COMBAT': 1,
               'POISON': 0.5,
               'SOL': 1,
               'VOL': 0.5,
               'PSY': 0.5,
               'INSECT': 0.5,
               'ROCHE': 2,
               'SPECTR': 0,
               'DRAGON': 1,
               'DARK': 2,
               'ACIER': 2,
               'FEE': 0.5}
              )

POISON = Type('POISON',
              (163, 62, 161),
              {'NORMAL': 1,
               'PLANTE': 2,
               'FEU': 1,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 1,
               'COMBAT': 1,
               'POISON': 0.5,
               'SOL': 0.5,
               'VOL': 1,
               'PSY': 1,
               'INSECT': 1,
               'ROCHE': 0.5,
               'SPECTR': 0.5,
               'DRAGON': 1,
               'DARK': 2,
               'ACIER': 2,
               'FEE': 0.5}
              )

SOL = Type('SOL',
           (226, 191, 101),
           {'NORMAL': 1,
            'PLANTE': 0.5,
            'FEU': 2,
            'EAU': 1,
            'ELEK': 2,
            'GLACE': 1,
            'COMBAT': 1,
            'POISON': 2,
            'SOL': 1,
            'VOL': 0,
            'PSY': 1,
            'INSECT': 0.5,
            'ROCHE': 2,
            'SPECTR': 1,
            'DRAGON': 1,
            'DARK': 1,
            'ACIER': 2,
            'FEE': 1}
           )

VOL = Type('VOL',
           (169, 143, 243),
           {'NORMAL': 1,
            'PLANTE': 2,
            'FEU': 1,
            'EAU': 1,
            'ELEK': 0.5,
            'GLACE': 1,
            'COMBAT': 2,
            'POISON': 1,
            'SOL': 1,
            'VOL': 1,
            'PSY': 1,
            'INSECT': 2,
            'ROCHE': 0.5,
            'SPECTR': 1,
            'DRAGON': 1,
            'DARK': 1,
            'ACIER': 0.5,
            'FEE': 1}
           )

PSY = Type('PSY',
           (249, 85, 135),
           {'NORMAL': 1,
            'PLANTE': 1,
            'FEU': 1,
            'EAU': 1,
            'ELEK': 1,
            'GLACE': 1,
            'COMBAT': 2,
            'POISON': 2,
            'SOL': 1,
            'VOL': 1,
            'PSY': 0.5,
            'INSECT': 1,
            'ROCHE': 1,
            'SPECTR': 1,
            'DRAGON': 1,
            'DARK': 0,
            'ACIER': 0.5,
            'FEE': 1}
           )

INSECT = Type('INSECT',
              (166, 185, 26),
              {'NORMAL': 1,
               'PLANTE': 2,
               'FEU': 0.5,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 1,
               'COMBAT': 0.5,
               'POISON': 0.5,
               'SOL': 1,
               'VOL': 0.5,
               'PSY': 2,
               'INSECT': 1,
               'ROCHE': 1,
               'SPECTR': 0.5,
               'DRAGON': 1,
               'DARK': 2,
               'ACIER': 0.5,
               'FEE': 0.5}
              )

ROCHE = Type('ROCHE',
             (182, 161, 54),
             {'NORMAL': 1,
              'PLANTE': 1,
              'FEU': 1,
              'EAU': 1,
              'ELEK': 1,
              'GLACE': 2,
              'COMBAT': 0.5,
              'POISON': 1,
              'SOL': 0.5,
              'VOL': 2,
              'PSY': 1,
              'INSECT': 2,
              'ROCHE': 1,
              'SPECTR': 1,
              'DRAGON': 1,
              'DARK': 1,
              'ACIER': 0.5,
              'FEE': 1}
             )

SPECTR = Type('SPECTR',
              (115, 87, 151),
              {'NORMAL': 0,
               'PLANTE': 1,
               'FEU': 1,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 1,
               'COMBAT': 1,
               'POISON': 1,
               'SOL': 1,
               'VOL': 1,
               'PSY': 2,
               'INSECT': 1,
               'ROCHE': 1,
               'SPECTR': 2,
               'DRAGON': 1,
               'DARK': 0.5,
               'ACIER': 1,
               'FEE': 1}
              )

DRAGON = Type('DRAGON',
              (111, 53, 252),
              {'NORMAL': 1,
               'PLANTE': 1,
               'FEU': 1,
               'EAU': 1,
               'ELEK': 1,
               'GLACE': 1,
               'COMBAT': 1,
               'POISON': 1,
               'SOL': 1,
               'VOL': 1,
               'PSY': 1,
               'INSECT': 1,
               'ROCHE': 1,
               'SPECTR': 1,
               'DRAGON': 2,
               'DARK': 1,
               'ACIER': 0.5,
               'FEE': 0}
              )

DARK = Type('DARK',
            (112, 87, 70),
            {'NORMAL': 1,
             'PLANTE': 1,
             'FEU': 1,
             'EAU': 1,
             'ELEK': 1,
             'GLACE': 1,
             'COMBAT': 0.5,
             'POISON': 1,
             'SOL': 1,
             'VOL': 1,
             'PSY': 2,
             'INSECT': 1,
             'ROCHE': 1,
             'SPECTR': 2,
             'DRAGON': 1,
             'DARK': 0.5,
             'ACIER': 1,
             'FEE': 0.5}
            )

ACIER = Type('ACIER',
             (183, 183, 206),
             {'NORMAL': 1,
              'PLANTE': 0.5,
              'FEU': 0.5,
              'EAU': 1,
              'ELEK': 0.5,
              'GLACE': 2,
              'COMBAT': 1,
              'POISON': 1,
              'SOL': 1,
              'VOL': 1,
              'PSY': 1,
              'INSECT': 1,
              'ROCHE': 2,
              'SPECTR': 1,
              'DRAGON': 1,
              'DARK': 1,
              'ACIER': 0.5,
              'FEE': 2}
             )

FEE = Type('FEE',
           (214, 133, 173),
           {'NORMAL': 1,
            'PLANTE': 0.5,
            'FEU': 1,
            'EAU': 1,
            'ELEK': 1,
            'GLACE': 1,
            'COMBAT': 2,
            'POISON': 0.5,
            'SOL': 1,
            'VOL': 1,
            'PSY': 1,
            'INSECT': 1,
            'ROCHE': 1,
            'SPECTR': 0,
            'DRAGON': 2,
            'DARK': 2,
            'ACIER': 0.5,
            'FEE': 1},
           )

